# shortcuts.py
from PyQt5.QtGui import QKeySequence

DEFAULT_SHORTCUTS = {
    "Quit": "Ctrl+Q",
    "Open Audio": "Ctrl+O",
    "Load JSON": "Ctrl+L",
    "Save JSON": "Ctrl+S",
    "Open Project": "Ctrl+Shift+O",
    "Save Project": "Ctrl+Shift+S",
    "Save Project As": "",
    "Export Default": "Ctrl+E",
    "Play/Pause": "Space",
    "Play/Pause (Alt)": "Ctrl+Space",
    "Stop/Play": "Esc",
    "Stop": "",
    "Jump Dialog": "J",
    "Insert Timestamp": "Ctrl+T",
    "Insert Speaker Tag": "Ctrl+Shift+T",
    "Toggle Highlight": "Ctrl+H",
    "Find": "Ctrl+F",
    "Find Next": "Ctrl+G",
    "Find Prev": "Ctrl+Shift+G",
    "Fold/Unfold": "Ctrl+Shift+F",
    "Format Bold": "Ctrl+B",
    "Format Italic": "Ctrl+I",
    "Format Underline": "Ctrl+U",
    "Jump to Cursor": "F5",
    "Increase Speed": "F4",
    "Decrease Speed": "F3",
    "Speed 25%": "Alt+1",
    "Speed 50%": "Alt+2",
    "Speed 75%": "Alt+3",
    "Speed 100%": "Alt+4",
    "Volume Up": "Up",
    "Volume Down": "Down",
    "Seek -0.1s": "Shift+Left",
    "Seek +0.1s": "Shift+Right",
    "Seek -0.5s": "Alt+Left",
    "Seek +0.5s": "Alt+Right",
    "Seek -1.0s": "Left",
    "Seek +1.0s": "Right",
    "Seek -5.0s": "Ctrl+Left",
    "Seek +5.0s": "Ctrl+Right",
    "Waveform 0.1s": "1",
    "Waveform 0.5s": "2",
    "Waveform 1.0s": "3",
    "Waveform 2.0s": "4",
    "Waveform 5.0s": "5",
}
