# shortcuts.py
import platform

DEFAULT_SHORTCUTS = {
    "Quit":                "Ctrl+Q",
    "Open Audio":          "Ctrl+Shift+O",
    "Load JSON":           "Ctrl+L",
    "Save JSON":           "Ctrl+Shift+S",
    "Open Project":        "Ctrl+O",
    "Save Project":        "Ctrl+S",
    "Save Project As":     "",
    "Export Default":      "Ctrl+E",
    "Play/Pause":          "Ctrl+P",
    "Play/Pause (Alt)":    "Ctrl+Shift+Space",
    "Stop/Play":           "Ctrl+Enter",
    "Stop":                "Shift+Esc",
    "Jump Dialog":         "Ctrl+J",
    "Insert Timestamp":    "Ctrl+T",
    "Insert Speaker Tag":  "Ctrl+Shift+T",
    "Toggle Highlight":    "Ctrl+H",
    "Find":                "Ctrl+F",
    "Find Next":           "Ctrl+G",
    "Find Prev":           "Ctrl+Shift+G",
    "Fold/Unfold":         "Ctrl+Shift+F",
    "Format Bold":         "Ctrl+B",
    "Format Italic":       "Ctrl+I",
    "Format Underline":    "Ctrl+U",
    "Add Comment":         "Ctrl+/",
    "Jump to Cursor":      "F5",
    "Increase Speed":      "Alt+Up",
    "Decrease Speed":      "Alt+Down",
    "Speed 25%":           "Alt+1",
    "Speed 50%":           "Alt+2",
    "Speed 75%":           "Alt+3",
    "Speed 100%":          "Alt+4",
    "Volume Up":           "Ctrl+Up",
    "Volume Down":         "Ctrl+Down",
    "Seek -0.1s":          "Ctrl+Left",
    "Seek +0.1s":          "Ctrl+Right",
    "Seek -0.5s":          "Alt+Left",
    "Seek +0.5s":          "Alt+Right",
    "Seek -1.0s":          "Ctrl+Alt+Left",
    "Seek +1.0s":          "Ctrl+Alt+Right",
    "Seek -5.0s":          "",
    "Seek +5.0s":          "",
    "Waveform 0.1s":       "Ctrl+1",
    "Waveform 0.5s":       "Ctrl+2",
    "Waveform 1.0s":       "Ctrl+3",
    "Waveform 2.0s":       "Ctrl+4",
    "Waveform 5.0s":       "Ctrl+5",
    "Set/Jump/Unset A":    "Ctrl+Alt+A",
    "Set/Jump/Unset B":    "Ctrl+Alt+B",
    "Toggle Loop":         "Ctrl+Alt+L",
}

# On Windows/Linux only, Preferences has a configurable shortcut.
# On macOS it uses the native Cmd+, via QAction.PreferencesRole, so we
# do NOT expose it in the shortcuts table at all on that platform.
if platform.system() != "Darwin":
    DEFAULT_SHORTCUTS["Preferences"] = "Ctrl+F12"
